import { ModuleWithProviders, NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  NbActionsModule,
  NbLayoutModule,
  NbMenuModule,
  NbSearchModule,
  NbSidebarModule,
  NbUserModule,
  NbContextMenuModule,
  NbButtonModule,
  NbSelectModule,
  NbIconModule,
  NbCardModule,
  NbInputModule,
  NbDatepickerModule,
  NbSpinnerModule,
  NbTooltipModule,
  NbBadgeModule,
  NbDialogModule,
  NbAccordionModule,
  NbRadioModule,
  NbCheckboxModule,
} from '@nebular/theme';
import { NbEvaIconsModule } from '@nebular/eva-icons';
import { NbMomentDateModule } from '@nebular/moment';

@NgModule({
  imports: [
    CommonModule,
    NbLayoutModule,
    NbUserModule,
    NbActionsModule,
    NbSearchModule,
    NbSidebarModule.forRoot(),
    NbContextMenuModule,
    NbSelectModule,
    NbButtonModule,
    NbRadioModule,
    NbIconModule,
    NbEvaIconsModule,
    NbCheckboxModule,
    NbCardModule,
    NbInputModule,
    NbMomentDateModule,
    NbSpinnerModule,
    NbTooltipModule,
    NbBadgeModule,
    NbAccordionModule,
  ],
  exports: [
    NbLayoutModule,
    NbMenuModule,
    NbUserModule,
    NbActionsModule,
    NbSearchModule,
    NbSidebarModule,
    NbContextMenuModule,
    NbSelectModule,
    NbRadioModule,
    NbButtonModule,
    NbIconModule,
    NbEvaIconsModule,
    NbCardModule,
    NbInputModule,
    NbDatepickerModule,
    NbMomentDateModule,
    NbSpinnerModule,
    NbTooltipModule,
    NbBadgeModule,
    NbDialogModule,
    NbAccordionModule,
    NbCheckboxModule,
  ],
  declarations: [],
})
export class ThemeModule {}
